### PR TITLE
Fix aliases in /etc/hosts for machines using a DNS suffix other than '.local'

### PR DESCRIPTION
**Pull request by wolf31o2**

### CODE REVIEW

**Comment by albertshau** [comment]
lgtm

**Comment by albertshau** [comment]
is it easy to add a unit test for this?

**Comment by wolf31o2** [comment]
I can write a test-suite for this cookbook. It wouldn't be too hard, but it wouldn't be something that gets tested, automatically.

**Comment by wolf31o2** [comment]
Remember, we still don't have unit tests on the provisioner. Many individual cookbooks with their own repositories have tests and are tested when things change in those repos, but there's not a global one for the provisioner (yet).

**Pull request merged**
