### PR TITLE
ability to disable multi-tenancy, in which case the tenant header

### PR DESCRIPTION
**Pull request by albertshau**
is ignored and the superadmin tenant is used everywhere a tenant
would normally be used.

### CODE REVIEW

**Comment by wolf31o2** [comment]
Should we set `server.multitenancy.enabled` to `false` by default for the singlenode/standalone?

**Comment by albertshau** [comment]
My first inclination is yes since the idea with standalone is to try and get up and running as simply as possible.

**Comment by wolf31o2** [comment]
I agree. Want to change that? Otherwise, LGTM... might want to get a Java dev to peek at it, though.

**Comment by albertshau** [comment]
I'm starting to wonder if this is more confusing than its worth.  Leaning towards not having this.

**Comment by wolf31o2** [comment]
Well, now that superadmin has cluster operation privileges, there's no reason someone couldn't have a single tenant and just use that to achieve single tenant status.

**Comment by albertshau** [comment]
yup. The inconsistencies this would introduce (how does one change # workers, max clusters, max nodes, and other tenant settings in a non-multi-tenant world? what about the UI?) outweigh the small convenience it brings. Abandoning this.

**Pull request closed without merging**
