### PR TITLE
disabling old ui tests since all new work should be going into the

### PR DESCRIPTION
**Pull request by albertshau**
new gui and because the tests are long and flaky.

### CODE REVIEW

**Comment by wolf31o2** [comment]
If we're dropping the old UI tests from being run, can we just remove them, entirely?

**Comment by wolf31o2** [comment]
Otherwise, LGTM on disabling...

**Comment by albertshau** [comment]
was thinking we'll do that once the new ui tests are ready

**Comment by albertshau** [comment]
we can also remove that top level pom at that point too...

**Comment by wolf31o2** [comment]
Sounds good.

**Pull request merged**
