### PR TITLE
Coopr-300: Move lease times away from milliseconds

### PR DESCRIPTION
**Pull request by artemmakogon**
@jwang47 Please review

### CODE REVIEW

**Comment by wolf31o2** [comment]
What about backwards compatibility with templates that use milliseconds? Is there a caskdata/coopr-templates PR to coincide with this?

**Comment by artemmakogon** [comment]
Support of milliseconds has not been removed. It's possible to setup lease times in two ways: milliseconds and in string format

**Comment by wolf31o2** [comment]
My bad. I missed where you're converting the strings to milliseconds internally. :+1:

**Comment by jwang47** [comment]
`LeaseDuration` is within the JSON right? In that case, could you also add some tests that use gson to serialize and deserialize JSON into `LeaseDuration` objects with tests using milliseconds and tests using the new timestamp format?

**Pull request closed without merging**
