### PR TITLE
[coopr-648] dropdown control hides in "Service Set" block in case if there are no available actions.

### PR DESCRIPTION
**Pull request by kpovetkin**
According to https://issues.cask.co/browse/COOPR-648

### CODE REVIEW

**Comment by gaarf** [comment]
code LGTM :+1:

**Comment by wolf31o2** [comment]
@gaarf is this good to merge, then?

**Comment by gaarf** [comment]
tests didn't pass... Little green checkmarks soothe my anxiety.

**Comment by wolf31o2** [comment]
Failure was due to provisioner due to a new rubocop. I'll fix that and send a PR for it, but this should be safe to merge (all server/UI tests passed)...

**Comment by wolf31o2** [comment]
Rubocop fixes are in #852

**Pull request merged**
