### PR TITLE
[ngui_ng-bind_usage] ng-bind added. Features have not been changed.

### PR DESCRIPTION
**Pull request by kpovetkin**

### CODE REVIEW

**Comment by gaarf** [comment]
LGTM, but IMHO most of these changes do nothing for end-user comfort. Some of the changes are hurtful to developer readability. WRT performance, it is basically a no-op.

**Comment by ajainarayanan** [comment]
@kpovetkin Thanks for taking the interest in creating a PR.. If I am not wrong most of them are just labels that will updated only once in the app's life time. Can we use `ngBindOnce`?

https://github.com/angular/angular.js/commit/4538e29f5e62de879fbfeb0cd9043d6fd965c3ae

Just a thought. These labels are not updated in every digest cycle and using ngBindOnce might reduce that dirty checking.

**Comment by kpovetkin** [comment]
It make sense. I'll update.

**Comment by kpovetkin** [comment]
Updated

**Comment by ajainarayanan** [comment]
Waiting on unit tests(travis) to pass.

**Comment by wolf31o2** [comment]
Build failed...

```
INFO [Chromium 37.0.2062 (Ubuntu)]: Connected on socket xMk97EeIUxcf5red2LOW with id 25747655
Chromium 37.0.2062 (Ubuntu): Executed 0 of 26 SUCCESS (0 secs / 0 secs)
ium 37.0.2062 (Ubuntu): Executed 1 of 26 SUCCESS (0 secs / 0.114 secs)
Chromium 37.0.2062 (Ubuntu) directive myConfigtoformfields should watch the provided config and set the model FAILED
    Expected '' to match 'foo label'.
    Error: Expected '' to match 'foo label'.
        at Object.<anonymous> (/home/travis/build/caskdata/coopr/coopr-ui/app/directives/configtoformfields/configtoformfields-unit-test.js:40:37)
```

**Comment by kpovetkin** [comment]
Everything is good for me. 

INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 36.0.1985 (Linux)]: Connected on socket avxSYwbSqFhS5e1AaJBx with id 71924302
Chrome 36.0.1985 (Linux): Executed 26 of 26 SUCCESS (0.2 secs / 0.192 secs)
WARN [Chrome 36.0.1985 (Linux)]: Disconnected (1 times)
ERROR [launcher]: Chrome crashed.

What karma, angular versions do you use?

**Comment by kpovetkin** [comment]
The same for chrome 38

INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 38.0.2125 (Linux)]: Connected on socket pI1fM3DDIzF4KB82b1zJ with id 45094498
Chrome 38.0.2125 (Linux): Executed 26 of 26 SUCCESS (0.196 secs / 0.191 secs)
WARN [Chrome 38.0.2125 (Linux)]: Disconnected (1 times)
ERROR [launcher]: Chrome crashed.

**Comment by kpovetkin** [comment]
Is there any way to get this file: /home/travis/build/caskdata/coopr/coopr-ui/npm-debug.log ?

**Comment by gaarf** [comment]
it's probably not wise to use ng-bind-once in directives. I would revert changes made to directive templates.

**Comment by kpovetkin** [comment]
The problem is not with ng-bind-once. It passes tests on my machines.

 It seems to be problem with travis environment. 
One of the possible ways to resolve an issue is to remove 'node_modules' and 'bower_components' directories from coopr-ui before building.

**Comment by ajainarayanan** [comment]
@kpovetkin given the short amount of time I would suggest replace `ng-bind-once` with `ng-bind` and check if travis passes. If not lets close this one for now and we can address this when we come back to coopr development. Not sure why `ng-bind-once` is failing

**Comment by kpovetkin** [comment]
ng-bind-once removed.
local tests passed:

npm test:
INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 38.0.2125 (Linux)]: Connected on socket sO0PWq_-SnbNtEq6zCxc with id 96290020
Chrome 38.0.2125 (Linux): Executed 26 of 26 SUCCESS (0.197 secs / 0.192 secs)

node ./node_modules/karma/bin/karma start test/karma-conf.js --no-auto-watch --single-run:
INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 38.0.2125 (Linux)]: Connected on socket boFyf7TgNVTQLsilzH59 with id 74086950
Chrome 38.0.2125 (Linux): Executed 26 of 26 SUCCESS (0.19 secs / 0.184 secs)

**Comment by ajainarayanan** [comment]
:+1: LGTM

**Pull request merged**
