### PR TITLE
[ui-build-maven-improvement] node_modules and bower_components removal commands added

### PR DESCRIPTION
**Pull request by kpovetkin**
Sometimes build process leads to corrupted UI build(Strict dependency injection problems could be seen browser console).

### CODE REVIEW

**Comment by wolf31o2** [comment]
I would much prefer there be separate build and clean targets for the build. We should only clean out these directories on a `mvn clean` not on every build.

**Comment by kpovetkin** [comment]
The reason why directories cleaning is in bash script is that on the second attempt to build an app artifact could be corrupted. It happens occasionally.

**Comment by wolf31o2** [comment]
Correct. Which is why there needs to be a way to clean the directories, but it should be done via a `mvn clean` command. It's fine if this command calls a script. We should never just blow away directories.

**Comment by wolf31o2** [comment]
Also, the clean should remove the generated `dist` directory, too.

**Comment by kpovetkin** [comment]
Updated according to comments.

**Comment by wolf31o2** [comment]
Build error is related to partials in server, so I am going to go ahead and merge this...

**Pull request merged**
