### PR TITLE
adding a description field to tenants.

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Comment by wolf31o2** [comment]
Same build error as I got. Merge `origin/develop`, please.

**Comment by wolf31o2** [comment]
Other than the build error, LGTM...

**Comment by albertshau** [comment]
already up-to-date, is there something that needs to be merged to develop first?

**Comment by wolf31o2** [comment]
Not as far as I know. I got the same Session ID errors in my build for `feature/rubocop-todo` and merging develop fixed it for me. Did you fetch/pull, first?

**Comment by albertshau** [comment]
yep, retrying build...

**Comment by albertshau** [comment]
hm... ui and integration testing has not changed in the past few days.  Will figure this out later and merge this PR since it's unrelated.

**Pull request merged**
