### PR TITLE
Feature/ui add sshuser

### PR DESCRIPTION
**Pull request by gaarf**
- adds `sshuser` field to imagetype provider form ui.
- refactored corresponding JS to be more readable.

Fixes #366

### CODE REVIEW

**Comment by wolf31o2** [comment]
Tests need to be updated. Also, you should update CHANGELOG.md with this and #366 and push it to this branch, too.

**Comment by gaarf** [comment]
@wolf31o2 it appears that the failure happens if UI submits a `providermap` with a `sshuser` key set to an empty string. Should the UI enforce presence of a sshuser string, or is there a default value?

**Comment by wolf31o2** [comment]
The UI should not enforce presence. We default them on the provisioner side. We _could_ default them on the UI to "root" but we've kept that sort of logic out of the UI, previously.

**Comment by gaarf** [comment]
@wolf31o2 actually the test failure happens no matter what the value of `sshuser`. If the key exists, the API responds with error. Are you sure backend is ready or am I missing something?

**Comment by wolf31o2** [comment]
I am sure that the backend is ready, as I am using this functionality (storing data to server via REST and provisioning a cluster).

**Comment by wolf31o2** [comment]
:+1: LGTM...

**Pull request merged**
