### PR TITLE
COOPR-567: Split server APIs to separate ports.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by albertshau** [comment]
travis is showing compilation errors.  Please fix.

**Comment by albertshau** [comment]
logic looks good to me.  But we should be able to configure both APIs differently.  For example, should be able to run the tasks API with 2-way tls but have no tls for the external api.

**Comment by albertshau** [comment]
lgtm, but travis consistently fails on ngui section. @gaarf @ajainarayanan is this a known issue?

**Comment by ghost** [comment]
PR updated according to last comments. Please review.

**Comment by albertshau** [comment]
passed today... not sure what is going on with travis but it is very flaky.

**Pull request merged**
